<a href="https://colab.research.google.com/github/maflorez08/Maira_FlorezBarreiro_KC/blob/main/taller1MairaFlorez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
# taller 1 
import numpy as np


In [112]:
#1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[[1,3,5,7,9]]=-1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [113]:
#2
a=np.arange(10)
a.reshape((2,5))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
#3
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [114]:
#4
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
(a[1::6])



array([2, 4])

In [88]:
#5
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a[0:4]



array([1, 2, 3, 4])

In [89]:
#6 
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[[1,3,4,],]



array([ 6,  9, 10])

In [115]:
#7
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])